#include<iostream>
using namespace std;

//int main()
//{
   // int n,x;
   // cin>>n;
   /* int sum=0;
    for(x=1;x<=n;x++)
    {
     sum=sum+x;
    
    }

    cout<<sum<<endl;*/

   /* while(n>0)
    {
     cout<<n<<endl;
     cin>>n;

    }*/


   /* do{

     cout<<n<<endl;
     cin>>n;
    }
    while(n>0); //here in do while loop 1st time input will be prtinted as it is....cause its not checking the condition first time.*/



   //print 1 to 100 without the multiple of 3// 
  /*int i , n;
  cin>>n;

  for(i=0;i<=n;i++)
  {
    if(i%3==0)
    {
        continue;// this helps to skip rhe next iteration of the loop
    }

    if(i>100)
    {
        break;// terminate the loop
    }
    cout<<i<<endl;
  }*/
    


    //check for prime nummbers//
 
 
 
 /*int main()

{


    int n,x;
    cin>>n;
    for(x=2;x<9;x++)
    {
        if(n%x==0)
        {
         cout<<"the no is not prime"<<endl; 
        
      break;
        }
    }     
    
   if(n==x)
   {
    cout<<"its prime"<<endl;
   }
   

   return 0;
    
}*/








 
